name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@master

     - name: Checkout move-language repo
       uses: actions/checkout@master
       with:
        repository: move-language/move
        path: ./move

     - name: Setup environment
       run: |
         ./move/scripts/dev_setup.sh -ybpt
         cargo install --path ./move/language/tools/move-cli

     - name: Build
       run: move build

     - name: Test
       run: move test

     - name: Prove
       run: |
         source ~/.profile
         move prove
